# OUTPUT_LANG_INDEX start from 2
generator-localization-sainbolt-app:
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=2 SPREADSHEET_ID=15mJ3eHzyPNn2aX0UIuG6C9ZwKRWZsL9cGQhNiX9kKLU GID_ID=system OUTPUT_FOLDER=../public/locales/vi/common.json
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=3 SPREADSHEET_ID=15mJ3eHzyPNn2aX0UIuG6C9ZwKRWZsL9cGQhNiX9kKLU GID_ID=system OUTPUT_FOLDER=../public/locales/en/common.json